In [ ]:
import pandas as pd
import numpy as np

# Primeiro parametro: O encoding='utf-8' é necessário para lidar com caracteres especiais / Segundo parametro: O sep =';' é usado para definir o separador do arquivo CSV, que neste caso é ponto e vírgula /  Terceiro parametro: O low_memory=False é usado para evitar o aviso de memória ao ler arquivos grandes / Quarto parametro: O decimal=',' é usado para definir o separador decimal, que neste caso é vírgula

df_vendas = pd.read_csv('vendas_tech.csv', low_memory=False) 
display(df_vendas)
df_gerentes = pd.read_excel('gerentes_lojas.xlsx')
display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [2]:
# Inspeção dos dados

display(df_vendas)
#display(df_vendas.head(10)) # Exibe as 10 primeiras linhas do DataFrame df_vendas
#display(df_vendas.tail(10)) # Exibe as 10 últimas linhas do DataFrame df_vendas
#display(df_vendas.sample(10)) # Exibe 10 linhas aleatórias do DataFrame df_vendas
#display(df_vendas.shape) # Exibe o número de linhas e colunas do DataFrame df_vendas
display(list(df_vendas.columns)) # Exibe os nomes das colunas do DataFrame df_vendas
#display(df_vendas.info()) # Exibe informações sobre o DataFrame df_vendas, como o número de entradas, tipos de dados e valores nulos
#display(df_vendas.describe()) # Exibe estatísticas descritivas do DataFrame df_vendas, como média, desvio padrão, valores mínimo e máximo

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

In [6]:
# Tratamento de dados

#display(df_vendas["Loja"]) # Usado para selecionar uma coluna do DataFrame df_vendas
#display(df_vendas[["Cliente", "Produto", "Preco_Unitario"]]) # Usado para selecionar múltiplas colunas do DataFrame df_vendas

# ----------- Colunas-------------

df_analise = df_vendas.drop(columns=["Data_Base"]) # Usado para remover a coluna "Data_Base" do DataFrame df_vendas

# ------------Nulos---------------

#df_analise = df_analise.dropna() # Usado para remover linhas com valores nulos do DataFrame df_analise
df_analise["Loja"] = df_analise["Loja"].fillna("Online") # Usado para preencher valores nulos na coluna "Loja" do DataFrame df_analise com o valor "Loja não informada"

# --------Tipos de dados----------

df_analise['Data'] = pd.to_datetime(df_analise['Data'], format='%Y-%m-%d') # Usado para converter a coluna "Data" do DataFrame df_analise para o tipo datetime

# --------Padronização de dados----------

df_analise["Loja"] = df_analise["Loja"].str.strip()  # Remove espaços em branco no início e no final dos valores da coluna "Loja" do DataFrame df_analise
df_analise["Loja"] = df_analise["Loja"].str.title()  # Usada para padronizar os valores da coluna "Loja" do DataFrame df_analise para o formato de título (primeira letra maiúscula e as demais minúsculas)

# ----------Duplicados------------

df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"]) # Usado para remover linhas duplicadas do DataFrame df_analise

display(df_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237