In [3]:
import pandas as pd
import numpy as np

tabela1 = pd.read_csv('vendas_tech.csv', low_memory=False)
tabela2 = pd.read_excel('gerentes_lojas.xlsx')

display(tabela1)
display(tabela2)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [4]:
display(tabela1) # Quantidade de linhas e colunas

#   display(tabela1.head(15)) --> Primeiras 15 linhas
#   display(tabela1.tail(15)) --> Últimas 15 linhas   
#   display(tabela1.sample(10)) --> Quantidade de linhas e colunas
#   display(tabela1.shape) --> Quantidade de linhas e colunas
#   display(tabela1.columns) --> Nomes das colunas
#   display(tabela1.info()) --> Informações sobre os dados
#   display(tabela1.describe()) --> Estatísticas dos dados

display(tabela1.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [5]:
# Tratamento de dados
#  
#display(tabela1['Loja'])
#display(tabela1[['Loja', 'Valor Venda']]

# Colunas

tabela_analise = tabela1.drop(columns='Data_Base') # Exclui a coluna  

display(tabela_analise)

# Valores vazio 

tabela_analise['Loja']= tabela_analise['Loja'].fillna('Online') # Substitui os valores vazios por 'Desconecido'

#  tabela_analise = tabela_analise.dropna() --> Exclui as linhas com valores vazios

tabela_analise['Loja'] = tabela_analise['Loja'].fillna(0) # Substitui os valores vazios por 0

# Tipos de dados

tabela_analise['Data'] = pd.to_datetime(tabela_analise['Data'], format="%Y-%m-%d") # Converte a coluna 'Data' para o tipo datetime

# Padronização de dados

tabela_analise['Loja'] = tabela_analise['Loja'].str.upper() # Converte os valores da coluna 'Loja' para maiúsculo
tabela_analise['Loja'] = tabela_analise['Loja'].str.strip() # Remove os espaços em branco da coluna 'Loja'  
tabela_analise['Loja'] = tabela_analise['Loja'].str.replace(' ', '_') # Substitui os espaços por underline na coluna 'Loja'
tabela_analise['Loja'] = tabela_analise['Loja'].str.title() # Substitui os traços por underline na coluna 'Loja'

# Duplicados

tabela_analise = tabela_analise.drop_duplicates(subset=['ID_Pedido', 'Loja'])  # Exclui as linhas duplicadas

display(tabela_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São_Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo_Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio_De_Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio_De_Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São_Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio_De_Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto_Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

In [16]:
#analisar --> filtrar

tabela_analise = tabela_analise.sort_values(by='Data')
tabela_analise = tabela_analise.reset_index(drop=True)

#.loc --> Nome coluna/ NOme linha 
id_pedido = 4

loja = tabela_analise.loc[3, "Loja"]
produto = tabela_analise.loc[3, "Produto"] 
cliente = tabela_analise.loc[3, "Cliente"]

print(loja, produto, cliente)
#.iloc ---> Por posição 
loja = tabela_analise.iloc[3, 2]
produto = tabela_analise.iloc[3, 3]
cliente = tabela_analise.iloc[3, 6]

print(loja, produto, cliente)
# condicional

# exportar pedaços da base

#tabela_vendas_sp = tabela_analise

display(tabela_analise)

Rio_De_Janeiro Notebook HP Cliente_15173
34825 2023-01-01 00:00:00 3200.0

,level_0,index,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,0,0,34750,2023-01-01,Rio_De_Janeiro,Notebook HP,3200.0,1,Cliente_9014
1,91,29,7963,2023-01-01,Porto_Alegre,Notebook Dell,3500.0,1,Cliente_15987
2,101,53,90270,2023-01-01,São_Paulo,Mouse Gamer,120.0,1,Cliente_6418
3,90,28,34825,2023-01-01,Rio_De_Janeiro,Notebook HP,3200.0,1,Cliente_15173
4,89,61,29187,2023-01-01,Recife,iPhone 14,5500.0,1,Cliente_2151
...,...,...,...,...,...,...,...,...,...
99995,99904,99997,82306,2024-12-30,Porto_Alegre,Mouse Gamer,120.0,1,Cliente_23016
99996,99903,99935,78449,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_19074
99997,99932,99967,42543,2024-12-30,Porto_Alegre,Teclado Mecânico,250.0,1,Cliente_22452
99998,99916,99985,10012,2024-12-30,Recife,"Monitor 27""",1200.0,1,Cliente_1799
99999,99999,99999,91693,2024-12-30,São_Paulo,iPhone 14,5500.0,1,Cliente_17362

In [ ]:
# analises por agrupamento